# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\20phi\OneDrive\Desktop\Петухон\ГУИ и где они обитают\weather.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(401, 302)
        Dialog.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255, 0, 66, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 142, 381, 151))
        self.label.setStyleSheet("font: 20pt \"Century Gothic\";\n"
"color: #000000;")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 401, 61))
        self.lineEdit.setStyleSheet("color: #aaff00;\n"
"font: 26pt \"Century Gothic\";\n"
"background-color: #1d1c21;\n"
"border: none;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 72, 381, 61))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    font: 20pt \"Century Gothic\";\n"
"    color: #f2b824;\n"
"    background-color: #1d1c21;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"    color: #f2c44e;\n"
"    background-color: #3a3c42;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #eb7b13\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Получить"))
        self.lineEdit.setText(_translate("Dialog", "Moscow"))
        self.pushButton.setText(_translate("Dialog", "Погода"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
